services:
  dev-db:
    image: postgres:18.3
    container_name: polyglot-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: d4vpas8w0rd13!!!
      POSTGRES_DB: polyglot-dev
    ports:
      - "3135:5432"
    volumes:
      - postgres-data-dev:/var/lib/postgresql

  keycloak:
    build: ./keycloak
    container_name: polyglot-keycloak-dev
    restart: unless-stopped
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/polyglot-realm.json:/opt/keycloak/data/import/polyglot-realm.json:ro
      - keycloak-data-dev:/opt/keycloak/data

volumes:
  postgres-data-dev:
  keycloak-data-dev:
