/**
 * Polyglot.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreditAdjustmentMode } from './creditAdjustmentMode';


export interface AdjustCreditsDto { 
    amount: number;
    mode: CreditAdjustmentMode;
}
export namespace AdjustCreditsDto {
}


