/**
 * Polyglot.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AvailableModelDto { 
    id: string;
    name: string;
    provider: string;
    currency: string;
    contextLength: number;
    inputModalities: Array<string>;
    outputModalities: Array<string>;
    supportedParameters: Array<string>;
    inputPricePer1M: number;
    outputPricePer1M: number;
}

