/**
 * Polyglot.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageDto } from './messageDto';


export interface ChatDetailDto { 
    id: string;
    title: string;
    createdAt: string;
    updatedAt: string;
    messages: Array<MessageDto>;
}

