/**
 * Polyglot.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SendMessageDto } from './sendMessageDto';


export interface ChatStreamPayload { 
    text?: string | null;
    result?: SendMessageDto;
    error?: string | null;
}

