/**
 * Polyglot.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatStreamPayloadType } from './chatStreamPayloadType';
import { SendMessageDto } from './sendMessageDto';


export interface ChatStreamPayload { 
    type?: ChatStreamPayloadType;
    text?: string | null;
    result?: SendMessageDto;
    error?: string | null;
    toolName?: string | null;
    toolInput?: string | null;
    toolOutput?: string | null;
}
export namespace ChatStreamPayload {
}


