/**
 * Polyglot.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ChatStreamPayloadType = {
    Chunk: 'Chunk',
    Done: 'Done',
    Error: 'Error'
} as const;
export type ChatStreamPayloadType = typeof ChatStreamPayloadType[keyof typeof ChatStreamPayloadType];

